name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: vars
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Zip extension
        run: |
          ZIP_NAME=${{ env.REPOSITORY_NAME }}_${{ env.TAG_NAME }}.zip
          zip -r $ZIP_NAME manifest.json background.js content_slack.js content_figma.js content_teams.js options.html options.js assets/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.REPOSITORY_NAME }}_${{ env.TAG_NAME }}.zip
          asset_name: ${{ env.REPOSITORY_NAME }}_${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip
