name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package the extension into a zip artifact
        run: |
          zip -r extension.zip manifest.json background.js content_slack.js content_figma.js content_teams.js options.html options.js assets/
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: extension.zip
